services:
  mongo:
    image: tiawidi/mongo:6.0.2
    container_name: simple-boook-store-mongo
    tty: true
    ports:
        - 27020:27017
    environment:
      - TZ='Asia/Jakarta'
      - MONGO_INITDB_ROOT_USERNAME=root.admin
      - MONGO_INITDB_ROOT_PASSWORD=root.admin.password
      - MONGO_INITDB_DATABASE=admin
    networks:
      - simple-book-store-net
    volumes:
      - mongo:/data/db
      - mongo:/data/configdb
  redis:
    image: tiawidi/redis:latest
    container_name: simple-book-store-redis
    tty: true
    environment:
      - TZ='Asia/Jakarta'
    ports:
      - "6379:6379"
    networks:
      - simple-book-store-net
volumes:
  mongo:
    driver: local
networks:
  simple-book-store-net:
    driver: bridge