development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: simple-book-store
      hosts:
        - 0.0.0.0:27020
      options:
        user: 'admin'
        password: 'password'
  # Configure Mongoid specific options. (optional)
  options:
    raise_not_found_error: false